spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/testmysql
    username: root
    password: R@kuten@250987
server:
   port: 9091       